/***********************************************************************************************
* Generated by buildinfo-maven-plugin (version: 1.0)
* Built: 19/01/2020 (18:10:52)
***********************************************************************************************/
package com.metaconflux.buildinfo.version;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class BuildInfo {

	public enum ProjectStage { PROOF_OF_CONCEPT, DEVELOPMENT, TEST, ALPHA, BETA, PRODUCTION}
	private final int year=2020;
	private final int month=1;
	private final int day=19;
	private final int hour=18;
	private final int minute=10;
	private final int second=52;
	public static final LocalDateTime buildDateTime = LocalDateTime.of(2020, 1, 19, 18, 10, 52);
	public static final String version = "1.0";
	public static final String productName = "buildinfo-maven-plugin";
	public static final String productUrl = "https://github.com/rabwallace/buildinfo-maven-plugin";
	public static final String author = "Rab Wallace";
	public static final String authorEmail = "javarab@yahoo.com";
	public static final ProjectStage projectStage = ProjectStage.TEST;
	public static final String copyright = "Opensource";
	public static final String shieldsioUrl = "https://img.shields.io/badge/buildinfo-v1.0-green";

	public BuildInfo(){}

	public String getProductName() { return productName; }

	public LocalDateTime getBuildDateTime() { return buildDateTime; }

	public String getVersion() { return version; }

	public ProjectStage getProjectStage() { return projectStage; }

	public String  getLocalBuildDateTime(String format) {
		final DateTimeFormatter formatter = DateTimeFormatter.ofPattern(format);
		return buildDateTime.format(formatter);
	}
}
