/***********************************************************************************************
* Generated by buildinfo-maven-plugin (version: 1.0)
* Built: 19/01/2020 (13:42:08)
***********************************************************************************************/
package com.metaconflux.buildinfo.version;
import java.time.LocalDateTime;

public class BuildInfo {

	public enum ProjectStage { PROOF_OF_CONCEPT, DEVELOPMENT, TEST, ALPHA, BETA, PRODUCTION}
	private final int year=2020;
	private final int month=1;
	private final int day=19;
	private final int hour=13;
	private final int minute=42;
	private final int second=8;
	public static LocalDateTime buildDateTime;
	public static final String version = "1.0";
	public static final String productName = "buildinfo-maven-plugin";
	public static final String productUrl = "https://github.com/rabwallace/buildinfo-maven-plugin";
	public static final String author = "Rab Wallace";
	public static final String authorEmail = "javarab@yahoo.com";
	public static final ProjectStage projectStage = ProjectStage.TEST;
	public static final String shieldsioUrl = "https://img.shields.io/badge/buildinfo-v1.0-green";

	public BuildInfo() {
		buildDateTime = LocalDateTime.of(year, month, day, hour, minute, second);
	}

	public String getProductName() { return productName; }

	public LocalDateTime getBuildDateTime() { return buildDateTime; }

	public String getVersion() { return version; }

	public ProjectStage getProjectStage() { return projectStage; }
}
